### ISSUE TITLE
Usability review from Carrie

### ISSUE THREAD

**Issue by djw8605** [unlhcc/HCCGo#105]
- [x] JobView - See submit file with the output & error 10ad8a80f296afa64d0972d8fad641012f4336a1
- [x] JobView - Status in the left column #124
- [x] JobView - Select all button for all of the output & error #133 
- [x] JobView - Save of the output & error. #133
- [x] Landing Page - Fix the coloring of the status icons 8b2c43e556047217f040e6708ace37dd49126293
- [x] Landing Page - Fix button when clicking on X to delete jobs from list. 	5878938
- [ ] File Transfer - Move or delete files in the file transfer.
- [x] Disconnection event capture! #107 
- [ ] A "new folder" button under File Management

**Comment by CarrieBrown** [comment]
A "new folder" button under File Management would be super handy as well.

**Comment by robogen** [comment]
For clarification on 'move' files, do they mean like drag and drop to move files into folders?

**Comment by CarrieBrown** [comment]
Yes.

**Comment by djw8605** [comment]
Eh, we're not trying to make a comprehensive file browser here.  @robogen, Don't worry about drag & drop moving of folders yet.  Lets focus on making the upload and download perfect.

**Comment by djw8605** [comment]
Good enough for now here.
